version: 2
updates:
  - package-ecosystem: 'gomod'
    pull-request-branch-name:
      separator: "-"  
    directory: './apps/untagged'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    pull-request-branch-name:
      separator: "-"  
    directory: './.github'
    schedule:
      interval: 'daily'